In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [2]:
train_logs = pd.read_csv('/Users/jjong/desktop/vscode/kaggle_src/linking-writing/train_logs.csv')
train_scores = pd.read_csv('/Users/jjong/desktop/vscode/kaggle_src/linking-writing/train_scores.csv')
test_logs = pd.read_csv('/Users/jjong/desktop/vscode/kaggle_src/linking-writing/test_logs.csv')
sample_submission = pd.read_csv('/Users/jjong/desktop/vscode/kaggle_src/linking-writing/sample_submission.csv')

In [3]:
train_logs

,id,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
0,001519c8,1,4526,4557,31,Nonproduction,Leftclick,Leftclick,NoChange,0,0
1,001519c8,2,4558,4962,404,Nonproduction,Leftclick,Leftclick,NoChange,0,0
2,001519c8,3,106571,106571,0,Nonproduction,Shift,Shift,NoChange,0,0
3,001519c8,4,106686,106777,91,Input,q,q,q,1,1
4,001519c8,5,107196,107323,127,Input,q,q,q,2,1
...,...,...,...,...,...,...,...,...,...,...,...
8405893,fff05981,3615,2063944,2064440,496,Nonproduction,Leftclick,Leftclick,NoChange,1031,240
8405894,fff05981,3616,2064497,2064497,0,Nonproduction,Shift,Shift,NoChange,1031,240
8405895,fff05981,3617,2064657,2064765,108,Replace,q,q,q => q,1031,240
8405896,fff05981,3618,2069186,2069259,73,Nonproduction,Leftclick,Leftclick,NoChange,1028,240
8405897,fff05981,3619,2070065,2070133,68,Input,.,.,.,1029,240

In [11]:
train_logs.groupby('id').sum()

,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
id,,,,,,,,,,
001519c8,3270403,2168798234,2169095477,297243,NonproductionNonproductionNonproductionInputIn...,LeftclickLeftclickShiftqqqqqqSpaceqqqSpaceqqqq...,LeftclickLeftclickShiftqqqqqqSpaceqqqSpaceqqqq...,NoChangeNoChangeNoChangeqqqqqq qqq qqqqqqq qqq...,1818445,327593
0022f953,3012285,1273271023,1273546414,275391,NonproductionNonproductionInputInputInputInput...,LeftclickShiftqqqqSpaceqqSpaceShiftqqqqqqqqqqq...,LeftclickShiftqqqqSpaceqqSpaceShiftqqqqqqqqqqq...,NoChangeNoChangeqqqq qq NoChangeqqqqqqqqqqqqqq...,1904809,448382
0042269b,8555316,3426641982,3427063183,421201,NonproductionNonproductionInputInputInputInput...,LeftclickShiftqqqqqqqSpaceqqqSpaceqqqqSpaceqqq...,LeftclickShiftqqqqqqqSpaceqqqSpaceqqqqSpaceqqq...,NoChangeNoChangeqqqqqqq qqq qqqq qqqq qqqq qq ...,3025946,805580
0059420b,1211346,1222211589,1222401185,189596,NonproductionNonproductionNonproductionNonprod...,LeftclickLeftclickShiftShiftShiftShiftShiftShi...,LeftclickLeftclickShiftShiftShiftShiftShiftShi...,NoChangeNoChangeNoChangeNoChangeNoChangeNoChan...,844188,161231
0075873a,3204246,1805499474,1805813176,313702,NonproductionNonproductionInputInputInputInput...,LeftclickShiftqqqqqqqqqqqSpaceqqSpaceqLeftclic...,LeftclickShiftqqqqqqqqqqqSpaceqqSpaceqLeftclic...,NoChangeNoChangeqqqqqqqqqqq qq qNoChangeqq NoC...,1518729,316585
...,...,...,...,...,...,...,...,...,...,...
ffb8c745,11231430,3488386746,3488886416,499670,NonproductionNonproductionNonproductionInputIn...,LeftclickTabLeftclickSpaceSpaceSpaceSpaceSpace...,LeftclickTabLeftclickSpaceSpaceSpaceSpaceSpace...,NoChangeNoChangeNoChange NoChangeqq qqqqq'...,3667989,1214860
ffbef7e5,3391710,2192480040,2192694261,214221,NonproductionNonproductionNonproductionInputIn...,LeftclickLeftclickShiftqqqqSpaceqqqqqqSpaceqqq...,LeftclickLeftclickShiftqqqqSpaceqqqqqqSpaceqqq...,NoChangeNoChangeNoChangeqqqq qqqqqq qqqqq qq q...,2661493,580726
ffccd6fd,4692516,3764472937,3764704517,231580,NonproductionNonproductionInputInputInputInput...,LeftclickLeftclickqqqqqqSpaceqqqqSpaceqSpaceqq...,LeftclickLeftclickqqqqqqSpaceqqqqSpaceqSpaceqq...,NoChangeNoChangeqqqqqq qqqq q qqqqqqq qqqqqqqq...,4009729,482696
ffec5b38,5256903,1869073112,1869362551,289439,NonproductionNonproductionInputInputInputInput...,LeftclickShiftqqqqqqqqBackspaceqqqSpaceqqqqqqq...,LeftclickShiftqqqqqqqqBackspaceqqqSpaceqqqqqqq...,"NoChangeNoChangeqqqqqqqqqqqq qqqqqqq, qqqqqq q...",3866542,667583
fff05981,6550390,3897099261,3897400496,301235,NonproductionNonproductionInputInputInputInput...,LeftclickLeftclickqqSpaceqqqqSpaceqqqqqqqqSpac...,LeftclickLeftclickqqSpaceqqqqSpaceqqqqqqqqSpac...,NoChangeNoChangeqq qqqq qqqqqqqq qq qqqqqqqqqq...,2132220,380376

In [4]:
test_logs

,id,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
0,0000aaaa,1,338433,338518,85,Input,Space,Space,,0,0
1,0000aaaa,2,760073,760160,87,Input,Space,Space,,1,0
2,2222bbbb,1,711956,712023,67,Input,q,q,q,0,1
3,2222bbbb,2,290502,290548,46,Input,q,q,q,1,1
4,4444cccc,1,635547,635641,94,Input,Space,Space,,0,0
5,4444cccc,2,184996,185052,56,Input,q,q,q,1,1

In [5]:
train_scores

            id  score
0     001519c8    3.5
1     0022f953    3.5
2     0042269b    6.0
3     0059420b    2.0
4     0075873a    4.0
...        ...    ...
2466  ffb8c745    3.5
2467  ffbef7e5    4.0
2468  ffccd6fd    1.5
2469  ffec5b38    5.0
2470  fff05981    4.0

[2471 rows x 2 columns]